version: "3.9"

services:
  dudanseai_bot_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db_bot:
          condition: service_healthy
      migrations:
        condition: service_completed_successfully

    pull_policy: build

    hostname: dudanseai_bot

    ports:
      - "8080:8080"
    environment:
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOST: ${DB_SERVICE_NAME}
      DB_PORT: ${DB_PORT_INTERNAL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped
        
  db_bot:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "127.0.0.1:${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
        - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    depends_on:
      db_bot:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations

    entrypoint: [
      "goose",
      "-dir", "/migrations",
      "postgres",
      "postgres://${DB_USER}:${DB_PASSWORD}@db_bot:${DB_PORT_INTERNAL}/${DB_NAME}?sslmode=disable",
      "up"
  ]

volumes:
  pgdata:

